# Generated by Django 4.2.1 on 2023-05-22 16:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True,unique=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'HOD'), (2, 'ManagerHOD'), (3, 'AllocatorHOD')], default=1, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllocatorHOD',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField(null=True)),
                ('registrationnumber', models.IntegerField(null=True)),
                ('faculty', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('profilepicture', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serialnumber', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('totalnumber', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipmentmanagementsystem.category')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('inventory_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('year', models.PositiveIntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerHOD',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField(null=True)),
                ('profilepicture', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('allocated_equipments', models.ManyToManyField(to='equipmentmanagementsystem.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('messages', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.managerhod')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAllocator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('messages', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('allocator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.allocatorhod')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.room'),
        ),
        migrations.CreateModel(
            name='Allocator',
            fields=[
                ('allocator_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=45, null=True)),
                ('allocator_username', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(max_length=45)),
                ('allocator_photo', models.CharField(blank=True, max_length=45, null=True)),
                ('phonenumber', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=45)),
                ('registration_number', models.IntegerField(blank=True, null=True)),
                ('faculty_name', models.CharField(blank=True, max_length=45, null=True)),
                ('speciality_name', models.CharField(blank=True, max_length=45, null=True)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('level', models.CharField(blank=True, max_length=45, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(max_length=255)),
                ('allocator_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipmentmanagementsystem.managerhod')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.allocation')),
                ('allocator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.allocatorhod')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='allocation',
            name='allocator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.allocatorhod'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.equipment'),
        ),
        migrations.CreateModel(
            name='AdminHOD',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
