# Generated by Django 4.2.1 on 2023-05-23 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentmanagementsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.equipment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.room')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('allocation_date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='allocatorhod',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('researcher', 'Researcher')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='allocatorhod',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='managerhod',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.AddField(
            model_name='request',
            name='allocator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.allocatorhod'),
        ),
        migrations.AddField(
            model_name='request',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.equipment'),
        ),
    ]
