# Generated by Django 4.2.1 on 2023-06-07 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentmanagementsystem', '0002_equipmentplanning_request_allocatorhod_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentplanning',
            name='room',
        ),
        migrations.AddField(
            model_name='equipmentplanning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentplanning',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.managerhod'),
        ),
        migrations.AddField(
            model_name='equipmentplanning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentplanning',
            name='day',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('saturday', 'Saturday')], default='saturday', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipmentplanning',
            name='end_time',
            field=models.TimeField(choices=[(datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00')], default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='equipmentplanning',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_plannings', to='equipmentmanagementsystem.equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentplanning',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipmentplanning',
            name='start_time',
            field=models.TimeField(choices=[(datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00')], default=datetime.time(8, 0)),
        ),
        migrations.CreateModel(
            name='EquipmentAllowedDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('saturday', 'Saturday')], max_length=10)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.equipment')),
                ('equipment_planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.equipmentplanning')),
            ],
        ),
    ]
