# Generated by Django 4.2.1 on 2023-06-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentmanagementsystem', '0003_remove_equipmentplanning_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('allocator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.allocatorhod')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.equipment')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.managerhod')),
            ],
        ),
    ]
