# Generated by Django 4.2.1 on 2023-06-08 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentmanagementsystem', '0004_equipmentallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatorhod',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.managerhod'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipmentmanagementsystem.managerhod'),
        ),
        migrations.AlterField(
            model_name='allocatorhod',
            name='registrationnumber',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
