# Generated by Django 4.2.1 on 2023-06-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentmanagementsystem', '0005_allocatorhod_manager_equipment_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='allocator',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='allocationreport',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='allocationreport',
            name='allocator',
        ),
        migrations.RemoveField(
            model_name='allocationreport',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='allocator',
            name='allocator_manager',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='notificationallocator',
            name='allocator',
        ),
        migrations.RemoveField(
            model_name='notificationmanager',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='request',
            name='allocator',
        ),
        migrations.RemoveField(
            model_name='request',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='Allocation',
        ),
        migrations.DeleteModel(
            name='AllocationReport',
        ),
        migrations.DeleteModel(
            name='Allocator',
        ),
        migrations.DeleteModel(
            name='NotificationAllocator',
        ),
        migrations.DeleteModel(
            name='NotificationManager',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
